# Generated by Django 4.1.2 on 2023-01-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(max_length=10000, verbose_name='Caption'),
        ),
    ]
