# Generated by Django 4.1.2 on 2023-01-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_post_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='reactions',
        ),
    ]
