# Generated by Django 4.1.2 on 2023-01-21 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='saved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
