# Generated by Django 4.1.2 on 2023-01-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_rename_date_of_birth_user_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('R', 'In A RelationShip'), ('X', 'Not Necessary')], default='X', max_length=30),
        ),
    ]
