# Generated by Django 4.1.2 on 2023-01-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('S', 'Single'), ('A', 'Married'), ('R', 'In A RelationShip'), ('N', 'Not Necessary')], default='N', max_length=30),
        ),
    ]
